# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: sajaltiwari
open_collective: sajaltiwari
ko_fi: sajaltiwari
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: sajaltiwari05
issuehunt: sajalt05
otechie: sajaltiwari
custom: ["rzp.io/l/sajaltiwari", "paypal.me/sajaltiwari"]
